version: "3.3"

networks:
  todo:
    driver: bridge

volumes:
  todo-db:
  todo-cache-cfg:
  todo-cache:

services:
  todo-api:
    build: ./
    container_name: todo-api
    command: go run ./cmd/main.go
    restart: unless-stopped
    ports:
      - "8000:8000"
    networks:
      - todo
    depends_on:
      - todo-db
      - todo-cache

  todo-db:
    container_name: todo-db
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - ./configs/postgres.env
    volumes:
      - todo-db:/var/lib/postgresql/data
    networks:
      - todo

  todo-cache:
    container_name: todo-cache
    image: redis:6.0.9-alpine
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - todo-cache:/var/lib/redis
      - todo-cache-cfg:/usr/local/etc/redis/redis.conf
    networks:
      - todo
